stages:
- name: Build and Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}
    env:
      PLUGIN_CUSTOM_DNS: 8.8.8.8,8.8.4.4
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment/docs-deployment.yaml
timeout: 60
notification: {}
