apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: docs
  name: docs-${CICD_GIT_BRANCH}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: docs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (HEAD)
        rancher.deployment.version: ${CICD_EXECUTION_ID}
      creationTimestamp: null
      labels:
        io.kompose.network/web: "true"
        io.kompose.service: docs
    spec:
      containers:
        - env:
            - name: PORT
              value: "8000"
          image: ${CICD_IMAGE}
          name: docs
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
